# Generated by Django 4.0.4 on 2022-05-17 04:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(db_column='ID', default=uuid.UUID('f82324ab-a5ac-4d1c-81c3-14aebd856c67'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(db_column='USERNAME', max_length=40, unique=True)),
                ('email', models.EmailField(db_column='EMAIL', max_length=255, null=True, unique=True)),
                ('first_name', models.CharField(db_column='FIRST_NAME', max_length=60, null=True)),
                ('last_name', models.CharField(db_column='LAST_NAME', max_length=60, null=True)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('is_email_verified', models.BooleanField(db_column='IS_EMAIL_VERIFIED', default=False)),
                ('is_superuser', models.BooleanField(db_column='IS_SUPERUSER', default=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='CREATED')),
                ('modified', models.DateTimeField(auto_now=True, db_column='MODIFIED')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'USER',
            },
        ),
    ]
