name: bidding CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9.7
      uses: actions/setup-python@v3
      with:
        python-version: 3.9.7
    - name: Setup and install dependencies
      run: |
        make setup-dev
    - name: Code Convention
      run: |
        make code-convention
    - name: Run Tests
      run: |
        make test
